export const FETCH_PAYBRIDGE_TOKEN = 'FETCH_PAYBRIDGE_TOKEN';
export const FETCH_PAYBRIDGE_REQUEST = 'FETCH_PAYBRIDGE_REQUEST';
export const FETCH_PAYBRIDGE_SUCCESS = 'FETCH_PAYBRIDGE_SUCCESS';
export const FETCH_PAYBRIDGE_FAILURE = 'FETCH_PAYBRIDGE_FAILURE';
export const FETCH_PAYBRIDGE_BANK_INFO_PGM = 'FETCH_PAYBRIDGE_BANK_INFO_PGM';
export const FETCH_PAYBRIDGE_BANK_INFO_TRF = 'FETCH_PAYBRIDGE_BANK_INFO_TRF';