export const FETCH_PAYBRIDGE_TOKEN = 'FETCH_PAYBRIDGE_TOKEN';
export const FETCH_PAYBRIDGE_REQUEST = 'FETCH_PAYBRIDGE_REQUEST';
export const FETCH_PAYBRIDGE_SUCCESS = 'FETCH_PAYBRIDGE_SUCCESS';
export const FETCH_PAYBRIDGE_FAILURE = 'FETCH_PAYBRIDGE_FAILURE';